### ISSUE TITLE
Problem running on Ubuntu 16.04

### ISSUE THREAD

**Issue by ragunathjawahar** [cesarferreira/international#2]
When I run `international --csv ~/Desktop/import.csv`, it results in the following error on my PC.

```
/usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- pry (LoadError)
    from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/lib/file_manager.rb:5:in `<top (required)>'
    from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/lib/international.rb:4:in `<top (required)>'
    from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /usr/local/lib/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/bin/international:3:in `<top (required)>'
    from /usr/local/bin/international:22:in `load'
    from /usr/local/bin/international:22:in `<main>'
```

When I googled, I found that `pry` wasn't installed. So I did a `sudo gem install pry`. After that, I get this

```
/var/lib/gems/2.3.0/gems/international-0.3.2/lib/international.rb:114:in `block (2 levels) in separate_languages': undefined method `last' for nil:NilClass (NoMethodError)
    from /var/lib/gems/2.3.0/gems/international-0.3.2/lib/international.rb:112:in `each'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/lib/international.rb:112:in `block in separate_languages'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/lib/international.rb:110:in `each'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/lib/international.rb:110:in `separate_languages'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/lib/international.rb:87:in `manage_opts'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/lib/international.rb:22:in `initialize'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/bin/international:5:in `new'
    from /var/lib/gems/2.3.0/gems/international-0.3.2/bin/international:5:in `<top (required)>'
    from /usr/local/bin/international:22:in `load'
    from /usr/local/bin/international:22:in `<main>'
```

**Comment by cesarferreira** [comment]
I had all of that fixed and forgot to push it! 
I'm sorry mate, check the new version and see if it's fixed.

**Comment by ragunathjawahar** [comment]
I did a `sudo gem update international` and my current version is `0.3.3`.

I still have the same issue.

``` java
/var/lib/gems/2.3.0/gems/international-0.3.3/lib/international.rb:114:in `block (2 levels) in separate_languages': undefined method `last' for nil:NilClass (NoMethodError)
    from /var/lib/gems/2.3.0/gems/international-0.3.3/lib/international.rb:112:in `each'
    from /var/lib/gems/2.3.0/gems/international-0.3.3/lib/international.rb:112:in `block in separate_languages'
    from /var/lib/gems/2.3.0/gems/international-0.3.3/lib/international.rb:110:in `each'
    from /var/lib/gems/2.3.0/gems/international-0.3.3/lib/international.rb:110:in `separate_languages'
    from /var/lib/gems/2.3.0/gems/international-0.3.3/lib/international.rb:87:in `manage_opts'
    from /var/lib/gems/2.3.0/gems/international-0.3.3/lib/international.rb:22:in `initialize'
    from /var/lib/gems/2.3.0/gems/international-0.3.3/bin/international:5:in `new'
    from /var/lib/gems/2.3.0/gems/international-0.3.3/bin/international:5:in `<top (required)>'
    from /usr/local/bin/international:22:in `load'
    from /usr/local/bin/international:22:in `<main>'
```

**Comment by cesarferreira** [comment]
Can you show me the first few lines of your .csv?

**Comment by ragunathjawahar** [comment]
It's the same one used in the example.

```
,pt,en,es
welcome_message,Bem vindo,welcome,bienvenido
goodbye,adeus,goodbye,adios
```
