### ISSUE TITLE
mac not can run the tool

### ISSUE THREAD

**Issue by fireantzhang** [cesarferreira/international#3]
I have installed this tool in my mac, when I run this tool has some errors occurred, can not find what is the cause, you can help answer some of the reasons you, thank you
![image](https://cloud.githubusercontent.com/assets/5302051/21606643/d0c8d856-d1eb-11e6-8c21-dceea3c0848c.png)

**Comment by ericntd** [comment]
same here:
```
❯ international --csv ~/Downloads/strings-v2.csv --platform android --output
/Library/Ruby/Gems/2.0.0/gems/international-0.3.4/lib/international.rb:33:in `create_options_parser': undefined method `options' for #<Array:0x007faafb8ae898> (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/international-0.3.4/lib/international.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/international-0.3.4/bin/international:5:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/international-0.3.4/bin/international:5:in `<top (required)>'
	from /usr/local/bin/international:23:in `load'
	from /usr/local/bin/international:23:in `<main>'
```

**Comment by jonnott** [comment]
Worked ok for me .. Mac OS 10.11.6, ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin15]

**Comment by fireantzhang** [comment]
@jonnott I have solved, upgrade the ruby version，thx

**Comment by dir-chen** [comment]
Hi, 

I have the same problem....:(

I'm using macOS 10.12.4, and gem 2.6.11

Any suggestion?

```
international --csv InfoPlist.strings.csv
/Library/Ruby/Gems/2.0.0/gems/international-0.3.4/lib/international.rb:33:in `create_options_parser': undefined method `options' for ["--csv", "InfoPlist.strings.csv"]:Array (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/international-0.3.4/lib/international.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/international-0.3.4/bin/international:5:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/international-0.3.4/bin/international:5:in `<top (required)>'
	from /usr/local/bin/international:23:in `load'
	from /usr/local/bin/international:23:in `<main>'


international
/Library/Ruby/Gems/2.0.0/gems/international-0.3.4/lib/international.rb:33:in `create_options_parser': undefined method `options' for ["-h"]:Array (NoMethodError)
	from /Library/Ruby/Gems/2.0.0/gems/international-0.3.4/lib/international.rb:20:in `initialize'
	from /Library/Ruby/Gems/2.0.0/gems/international-0.3.4/bin/international:5:in `new'
	from /Library/Ruby/Gems/2.0.0/gems/international-0.3.4/bin/international:5:in `<top (required)>'
	from /usr/local/bin/international:23:in `load'
	from /usr/local/bin/international:23:in `<main>'
```

**Comment by mladenrakonjac** [comment]
Doesn't work on:
Mac-mini:~ mladenrakonjac$ ruby -v
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin15]
Mac-mini:~ mladenrakonjac$ gem -v
2.6.13

**Comment by chetbox** [comment]
Can anyone tell me which version of ruby this _does_ work with?

**Comment by jschnall** [comment]
I'm having the same issue.

ruby -v:  ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
gem -v:  2.6.14

**Comment by chetbox** [comment]
We're now using (a fork of) Babelish: https://github.com/RideBeeline/Babelish

**Comment by igorkislyuk** [comment]
Same issue
